### ISSUE TITLE
cannot install sage

### ISSUE THREAD

**Issue by s1752729916** [raphaelsulzer/compod#1]
hi,
thanks for your work! the install.sh failed to install the package sage and run `conda install conda-forge::sage` also failed. would you provide some guidances on how to install this package?

**Comment by raphaelsulzer** [comment]
Hi, 

thanks for your interest in this work.

You can find some installation instruction for SageMath here: https://doc.sagemath.org/html/en/installation/index.html

On Linux or macOS 'conda install sage' should work just fine with e.g. Python 3.10.10, but not with Python 3.11 or 3.12 though I think.

On Windows it is more difficult to install SageMath. The easiest method I found was to use 'Windows Subsystem for Linux (WSL)'. E.g. with the commands below you can start an Ubuntu session in which the install.sh script should work.

In a power shell simply run:
```
wsl --install Ubuntu
Ubuntu
```

**Comment by fangyipeng** [comment]
Dr. Raphael, I see that your algorithm relies heavily on collision detection between planes. Is your algorithm so dependent on plane accuracy detection? Have you ever worked on more complex scenarios with more than 1000 faces? Why is my result not good? How do you split the plane of your example\data\sphere? Do you use Ransac or is the model already split? Looking forward to your reply, Shanghai, China

**Comment by raphaelsulzer** [comment]
Hi,

yes, the accuracy of the algorithm depends mainly on the accuracy of the input point cloud and the planes detected from it.

The algorithm should easily handle more than 1000 input planes.

For extracting planes from point clouds you can for example use PSDR (https://github.com/raphaelsulzer/psdr). 

If you have any further questions please open a new issue.

Kind regards,
Raphael
