### ISSUE TITLE
Non watertight mesh

### ISSUE THREAD

**Issue by sanskar107** [raphaelsulzer/compod#2]
It it possible to do minor changes in the code to export a non watertight mesh ?

**Comment by raphaelsulzer** [comment]
it should already be possible by calling [PolyhedralComplex.save_colored_soup(filename)](https://github.com/raphaelsulzer/compod/blob/7e4182f81bdf85bf00895192eca74490478f637d/pycompod/complex.py#L496). If it doesn't work out of the box let me know and I'll have a look.

**Comment by sanskar107** [comment]
@raphaelsulzer thanks for your response. I tried saving the colored soup, but it seems it also saves a watertight mesh.
One thing to notice is that all the faces have some unique color except for the faces that shouldn't be in the water tight mesh. So, I guess we can prune the faces which have a default color (pinkish). Is this expected ? or do you have other suggestions to get non watertight mesh ?

**Comment by raphaelsulzer** [comment]
I think we mean different things when we talk about a "non-watertight" mesh.

The pink color is assigned to faces that come from the bounding box, and not from input planes. Maybe what you actually want is to simply do not add bounding box planes?

You can achieve that by not calling the PolyhedralComplex.add_bounding_box_planes() function.

So in the example do:

```
file = "data/{}/convexes_refined/file.npz".format(model)
vg = VertexGroup(file,verbosity=20)
cc = PolyhedralComplex(vg,device='gpu',verbosity=20)

cc.construct_partition()
# cc.add_bounding_box_planes()  ### remove this line
cc.label_partition(mode="normals")
```

Hope that helps.
